version: '3.9'

services:
# DATABASE SERVICE
  db:
    image: postgres:16-alpine
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - postgresenv
    volumes:
      - ./init_db_data:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    depends_on:
      - db
    restart: always
    ports:
      - "8888:80"
    env_file:
      - pgadminenv
    volumes:
      - pgadmin-data:/var/lib/pgadmin


# SPARK SERVICE
  spark:
    container_name: spark
    image: kumarroshandot/spark-postgres
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - /tmp:/data
    ports:
      - '8100:8080'
  spark-worker-1:
    image: kumarroshandot/spark-postgres
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - /tmp:/data
  spark-worker-2:
    image: kumarroshandot/spark-postgres
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - /tmp:/data

volumes:
  pgadmin-data: